### ISSUE TITLE
failed installing on kibana 5.0.0 on Ubuntu 

### ISSUE THREAD

**Issue by agonen** [ommsolutions/kibana_ext_metrics_vis#1]
root@vagrant-ubuntu-trusty-64:/usr/share/kibana# ./bin/kibana-plugin install https://github.com/ommsolutions/kibana_ext_metrics_vis/archive/0.1.0.zip
Attempting to transfer from https://github.com/ommsolutions/kibana_ext_metrics_vis/archive/0.1.0.zip
Transferring 720161 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by olsn** [comment]
Did it also not work by extracting the contents to the plugins-directory manually?
Or is it just the installer?

**Comment by Tonyko** [comment]
I installed manually plugin with #2 and it's working for me (Kibana 5.0.0).

**Comment by olsn** [comment]
okay thanks @Tonyko I will verify and merge this later today

**Comment by olsn** [comment]
I have created a fixed release-package and updated the readme with a link to the fixed archive:

```sh
$ ./bin/kibana-plugin install https://github.com/ommsolutions/kibana_ext_metrics_vis/releases/download/0.1.0/extended_metric_vis.zip
```
