### ISSUE TITLE
Support for kibana 5.5

### ISSUE THREAD

**Issue by source-ram** [ommsolutions/kibana_ext_metrics_vis#13]
Requesting changes to make it compatible  to Kibana 5.5.0

**Comment by RMKD** [comment]
You may be having errors related to the import syntax for 5.5, see https://github.com/elastic/kibana/issues/12707

**Comment by iFedix** [comment]
There is a pull request pending to add the support for Kibana 5.5.0.

**Comment by sergitopo** [comment]
With the changes of your pull request @iFedix  kibana does not crash now, but there is no the extended metric visualization in the visualizations types in /app/kibana#/visualize/new?_g=(). Does this happens to you as well?

**Comment by iFedix** [comment]
No. This does not happen to me (I am running 5.0.0 kibana version).
![capture](https://user-images.githubusercontent.com/23638108/28669958-cc4a9c9c-72d6-11e7-988a-2332ded0ce5f.PNG)

**Comment by MohammadMazraeh** [comment]
@iFedix 5.0.0 or 5.5.0 ?

**Comment by iFedix** [comment]
@MohammadMazraeh and @sergitopo, uhh sorry! I was talking about Kibana 5.5.0 not 5.0.0. I corrected the comment above!

**Comment by sergitopo** [comment]
Yes @iFedix , the plugin is loaded succesfully in 5.5.0, I was expecting to find it in the data secction of visualization menu and not in others, thank you!

**Comment by alumino** [comment]
Encountered this issue while upgrading to v. 5.5
Applied the changes proposed by @iFedix on extended_metric_vis.js and extended_metric_vis_controller.js and kibana is now loading successfully

The problem now is that the extended metric visualizations are not working.

We can select the extended metric, select the index from which the visualization is going to be based and get to the extended metric visualization window, but no metric values or labels are displayed, only the table at the bottom with the data.

Turned on the javascript debugger to see if the plugin throws an exception and found this error at commons.bundle.js:38:11454 

Error: Expected private module "undefined" to be a function
identify@http://localhost:5601/bundles/commons.bundle.js?v=15382:90:23797
Private@http://localhost:5601/bundles/commons.bundle.js?v=15382:90:24789
@http://localhost:5601/bundles/kibana.bundle.js?v=15382:285:13947
invoke@http://localhost:5601/bundles/commons.bundle.js?v=15382:36:1271
$ControllerProvider/this.$get</</instantiate<@http://localhost:5601/bundles/commons.bundle.js?v=15382:37:17184
nodeLinkFn@http://localhost:5601/bundles/commons.bundle.js?v=15382:36:26059
compositeLinkFn@http://localhost:5601/bundles/commons.bundle.js?v=15382:36:17257
compile/<@http://localhost:5601/bundles/commons.bundle.js?v=15382:36:15813
TemplateRenderbot@http://localhost:5601/bundles/kibana.bundle.js?v=15382:265:14310
TemplateVisTypeProvider/TemplateVisType.prototype.createRenderbot@http://localhost:5601/bundles/kibana.bundle.js?v=15382:265:13596
link/<@http://localhost:5601/bundles/kibana.bundle.js?v=15382:250:20910
link/prereq</</<@http://localhost:5601/bundles/kibana.bundle.js?v=15382:250:20317
$digest@http://localhost:5601/bundles/commons.bundle.js?v=15382:39:2869
$apply@http://localhost:5601/bundles/commons.bundle.js?v=15382:39:5026
$LocationProvider/this.$get</<@http://localhost:5601/bundles/commons.bundle.js?v=15382:38:9125
dispatch@http://localhost:5601/bundles/commons.bundle.js?v=15382:28:18652
add/elemData.handle@http://localhost:5601/bundles/commons.bundle.js?v=15382:28:15595
  commons.bundle.js:38:11454

Error: $scope.renderbot is null
link/<@http://localhost:5601/bundles/kibana.bundle.js?v=15382:250:21818
link/prereq</</<@http://localhost:5601/bundles/kibana.bundle.js?v=15382:250:20317
$digest@http://localhost:5601/bundles/commons.bundle.js?v=15382:39:2869
$apply@http://localhost:5601/bundles/commons.bundle.js?v=15382:39:5026
done@http://localhost:5601/bundles/commons.bundle.js?v=15382:37:25016
completeRequest@http://localhost:5601/bundles/commons.bundle.js?v=15382:37:28702
createHttpBackend/</xhr.onload@http://localhost:5601/bundles/commons.bundle.js?v=15382:37:29634

Does anyone have encountered this problem too?

**Comment by abderr080** [comment]
I am using kibana 5.5.0 and I have the same problem as @alumino after applying the changes proposed by @iFedix . Is anyone has a solution for this issue?

**Comment by iFedix** [comment]
I found out that I have the same problem lol. Maybe I tried that out on another cluster where I have another version of the elastic stack. For now I close the pull request. Need to investigate to find the problem. Anyway the logs don't say too much.. mmm

**Comment by meera-g** [comment]
Is there any update on this?

**Comment by v01t** [comment]
version 5.5.1:
`Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://kibana:5601/bundles/kibana.bundle.js?v=15405:262)
    at window.onerror (http://kibana:5601/bundles/commons.bundle.js?v=15405:90:20880)`

**Comment by ced4death** [comment]
It is necessary to replace in the file "public/extended_metric_vis_controller.js"
AggResponseTabifyTabifyProvider
by
AggResponseTabifyProvider

line 2 and 7

and it works :)

**Comment by sergitopo** [comment]
:) . Greate, easy solution it was, but nobody found it before XD

**Comment by alumino** [comment]
Did anyone confirmed this solution?
I made the changes suggested, now the plugin loads without errors, but I still can't see anything besides the data table. The label containing the metric is not displayed.

Any suggestions?

**Comment by hanzohan** [comment]
did anyone have a solution? my label containing metric is not displayed. 
im using kibana 5.5.0. any suggestion please?

**Comment by AmOrFeU86** [comment]
I have the same problem as @v01t: 

Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15543:261)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15543:90:22028)

I've tried to apply the solution of @ced4death but it keeps giving me the same error after restarting Kibana.

Kibana version: 5.6.2
Elasticsearch version: 5.6.2

Does anyone have a solution?¿

**Comment by eloirobe** [comment]
I have the same problem like @AmOrFeU86

**Comment by peronha** [comment]
Me too @eloirobe

**Comment by jworksinc** [comment]
Same issue on 5.6.4.

**Comment by olsn** [comment]
I've merged pullrequest #15 and tested with 5.5.0, 5.5.2 and 5.6.5 - Thanks for providing the fix @ced4death  - which all seemed to work with my quick tests - also i've created release-versions for those kibana-releases - please check the readme-file for details on how to install.

I'll close this for now - but feel free to reply if there are still issues with one of those versions
