### ISSUE TITLE
Kibana 6.x (6.3.0) support

### ISSUE THREAD

**Issue by v01t** [ommsolutions/kibana_ext_metrics_vis#17]
Hello,

is there any plans to make this plugin works with latest kibana version?

Thanks for a great plugin.

**Comment by acukan** [comment]
hear hear

**Comment by juliojs** [comment]
+1

**Comment by SamikshaJain** [comment]
Do we have support for this in 6.3.0?

**Comment by enenkel** [comment]
We skipped loads of releases and went directly to 7.4.2:
https://github.com/ommsolutions/kibana_ext_metrics_vis/releases/tag/7.4.2
It's unlikely that there will be a version 6.x release.
