### ISSUE TITLE
Support for Kibana 7.x

### ISSUE THREAD

**Issue by acommend** [ommsolutions/kibana_ext_metrics_vis#20]
Are there any plans to support Kibana 7.x?

**Comment by enenkel** [comment]
There are, but like the other releases, we won't support any 7.x version, but only specific ones.

This is currently the only release for version 7.x:
https://github.com/ommsolutions/kibana_ext_metrics_vis/releases/tag/7.4.2

However, I don't expect many changes in this legacy module within the 7.x major release of Kibana, so you might just be able to change the version in the package.json as specified in the readme.
