### ISSUE TITLE
Error installing ext_metrics on Kibana 5.0.0 using bin/kibana-plugin install https://github.com/ommsolutions/kibana_ext_metrics_vis/releases/download/0.1.0/extended_metric_vis.zip

### ISSUE THREAD

**Issue by younes778** [ommsolutions/kibana_ext_metrics_vis#3]
Installing the plugin i'm getting this error :
ERROR in ./plugins/area3d_vis/public/area3d_vis_controller.js
    Module not found: Error: Cannot resolve module 'vis' in /usr/share/kibana/plugins/area3d_vis/public
     @ ./plugins/area3d_vis/public/area3d_vis_controller.js 19:11-25

**Comment by olsn** [comment]
`area3d_vis` is a different plugin - this should have nothing to do with the `extended_metric_vis` in fact this plugin (when using the plugin-installer) does not even have access to the folder `./plugins/area3d_vis/`
Have you checked with https://github.com/JuanCarniglia/area3d_vis yet ?

**Comment by younes778** [comment]
You're right sorry for disturbance. It works correctly, thank you for this plugin 👍
