### ISSUE TITLE
Display Options

### ISSUE THREAD

**Issue by SMAPPER** [ommsolutions/kibana_ext_metrics_vis#7]
Does this plugin support any display options such as limit the number of decimal places shown or show a percentage sign after a calculated number? This plugin shows a lot of promise.

**Comment by patil-akshay** [comment]
How to use it for bucket aggregations?

**Comment by tcarette** [comment]
I added a controller to change the display format using numeral.js in my fork. I wanted to add the possibility to define it in each ouput separately before making a pull request, but I don't have the time to do it right now.

**Comment by olsn** [comment]
You can actually use any JavaScript in the input so you could add some JavaScript-Formatting there yourself (at least as a "hack") - Also, there's a pull-request here: #12 that you could use - unfortunately I did not have time yet to check it out.
